- name: Copy custom index.html to host
  copy:
    src: index.html
    dest: /tmp/index.html
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Nginx container

- name: Ensure Nginx container is running
  community.docker.docker_container:
    name: hello
    image: nginx:latest
    state: started
    ports:
      - "80:80"
    volumes:
      - /tmp/index.html:/usr/share/nginx/html/index.html:ro

